# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
#paginate: 5
#gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://rawatrahul.github.io/
baseurl: /
title: Rahul Rawat
author: Rahul Rawat
description: Personal blog and resume
avatar: profile.jpg
email: rahulrawat593@gmail.com
github: rawatrahul # username
twitter: rahulsalutes
linkedin: irrawat
#stackoverflow: 
facebook: rawatrahul



# needed for travis-ci build
exclude: [vendor]
